repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: v23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.4.0
    hooks:
    -   id: doctoc
        args:
          - --title
          - "## Table of Contents"
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.1
  hooks:
      - id: markdown-link-check
        args: [-q]