repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
    -   id: doctoc
        args:
          - --title
          - "## Table of Contents"
